services:
  - type: web
    name: ugboard-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ADMIN_TOKEN
        value: admin-ug-board-2025
      - key: INJECT_TOKEN
        value: inject-ug-board-2025
      - key: INTERNAL_TOKEN
        value: 1994199620002019866
    healthCheckPath: /health
    autoDeploy: true
